package views;

import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 * @author Lucas da Paz
 */
public class App extends JFrame {
	public App() {
		initComponents();
		setVisible(true);
	}

	private void mostraFrameInterno(JInternalFrame frame) {
		desktopPane.add(frame);
		frame.moveToFront();
		frame.requestFocus();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    desktopPane = new javax.swing.JDesktopPane();
    menuBar = new javax.swing.JMenuBar();
    menuGeral = new javax.swing.JMenu();
    novoDroneMenuItem = new javax.swing.JMenuItem();
    novoTransporteMenuItem = new javax.swing.JMenuItem();
    separadorMenuGeral1 = new javax.swing.JPopupMenu.Separator();
    processarTransporteMenuItem = new javax.swing.JMenuItem();
    situacaoTransporteMenuItem = new javax.swing.JMenuItem();
    separadorMenuGeral2 = new javax.swing.JPopupMenu.Separator();
    sairMenuItem = new javax.swing.JMenuItem();
    menuRelatorio = new javax.swing.JMenu();
    relatorioGeralMenuItem = new javax.swing.JMenuItem();
    relatorioTransportesMenuItem = new javax.swing.JMenuItem();
    menuArquivo = new javax.swing.JMenu();
    salvarDadosMenuItem = new javax.swing.JMenuItem();
    carregarDadosMenuItem = new javax.swing.JMenuItem();
    separatorMenuArquivo1 = new javax.swing.JPopupMenu.Separator();
    simulacaoMenuItem = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("ACME Air Drones");
    setPreferredSize(new java.awt.Dimension(900, 700));

    desktopPane.setPreferredSize(new java.awt.Dimension(750, 600));

    javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
    desktopPane.setLayout(desktopPaneLayout);
    desktopPaneLayout.setHorizontalGroup(
      desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 750, Short.MAX_VALUE)
    );
    desktopPaneLayout.setVerticalGroup(
      desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 600, Short.MAX_VALUE)
    );

    menuGeral.setText("Geral");
    menuGeral.setMargin(new java.awt.Insets(3, 15, 3, 15));

    novoDroneMenuItem.setText("Novo Drone");
    novoDroneMenuItem.setToolTipText("Cadastrar um novo drone no sistema");
    novoDroneMenuItem.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        abreCadastroDrone(evt);
      }
    });
    menuGeral.add(novoDroneMenuItem);

    novoTransporteMenuItem.setText("Novo Transporte");
    novoTransporteMenuItem.setToolTipText("Cadastrar um novo transporte no sistema");
    novoTransporteMenuItem.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        abreNovoTransporte(evt);
      }
    });
    menuGeral.add(novoTransporteMenuItem);
    menuGeral.add(separadorMenuGeral1);

    processarTransporteMenuItem.setText("Processar Transportes");
    processarTransporteMenuItem.setToolTipText("Processar os transportes na situação \"PENDENTE\"");
    processarTransporteMenuItem.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        abreProcessamentoTransportes(evt);
      }
    });
    menuGeral.add(processarTransporteMenuItem);

    situacaoTransporteMenuItem.setText("Situação Transporte");
    situacaoTransporteMenuItem.setToolTipText("Alterar a situação de um transporte");
    situacaoTransporteMenuItem.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        abreSituacaoTransporte(evt);
      }
    });
    menuGeral.add(situacaoTransporteMenuItem);
    menuGeral.add(separadorMenuGeral2);

    sairMenuItem.setText("Sair");
    sairMenuItem.setToolTipText("Encerrar a aplicação");
    sairMenuItem.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        encerrarAplicacao(evt);
      }
    });
    menuGeral.add(sairMenuItem);

    menuBar.add(menuGeral);

    menuRelatorio.setText("Relatório");
    menuRelatorio.setMargin(new java.awt.Insets(3, 15, 3, 15));

    relatorioGeralMenuItem.setText("Relatório Geral");
    relatorioGeralMenuItem.setToolTipText("Gerar relatório com informações de todos os drones e transportes");
    relatorioGeralMenuItem.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        abreRelatorioGeral(evt);
      }
    });
    menuRelatorio.add(relatorioGeralMenuItem);

    relatorioTransportesMenuItem.setText("Relatório Transportes");
    relatorioTransportesMenuItem.setToolTipText("Gerar relatório com informações de todos os transportes");
    relatorioTransportesMenuItem.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        abreRelatorioTransportes(evt);
      }
    });
    menuRelatorio.add(relatorioTransportesMenuItem);

    menuBar.add(menuRelatorio);

    menuArquivo.setText("Arquivo");
    menuArquivo.setMargin(new java.awt.Insets(3, 15, 3, 15));

    salvarDadosMenuItem.setText("Salvar Dados");
    salvarDadosMenuItem.setToolTipText("Salvar todos os dados do sitema");
    menuArquivo.add(salvarDadosMenuItem);

    carregarDadosMenuItem.setText("Carregar Dados");
    carregarDadosMenuItem.setToolTipText("Carregar dados salvos para o sistema");
    menuArquivo.add(carregarDadosMenuItem);
    menuArquivo.add(separatorMenuArquivo1);

    simulacaoMenuItem.setText("Simulação");
    simulacaoMenuItem.setToolTipText("Realizar leitura de dados de simulação");
    simulacaoMenuItem.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        abreSimulacao(evt);
      }
    });
    menuArquivo.add(simulacaoMenuItem);

    menuBar.add(menuArquivo);

    setJMenuBar(menuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void abreCadastroDrone(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abreCadastroDrone
		mostraFrameInterno(new CadastroDrone());
  }//GEN-LAST:event_abreCadastroDrone

  private void abreProcessamentoTransportes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abreProcessamentoTransportes
		mostraFrameInterno(new ProcessamentoTransportes());
  }//GEN-LAST:event_abreProcessamentoTransportes

  private void encerrarAplicacao(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encerrarAplicacao
		dispose();
		dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
  }//GEN-LAST:event_encerrarAplicacao

  private void abreRelatorioGeral(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abreRelatorioGeral
		mostraFrameInterno(new RelatorioGeral());
  }//GEN-LAST:event_abreRelatorioGeral

  private void abreRelatorioTransportes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abreRelatorioTransportes
		mostraFrameInterno(new RelatorioTransportes());
  }//GEN-LAST:event_abreRelatorioTransportes

  private void abreNovoTransporte(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abreNovoTransporte
		mostraFrameInterno(new CadastroTransporte());
  }//GEN-LAST:event_abreNovoTransporte

  private void abreSituacaoTransporte(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abreSituacaoTransporte
		mostraFrameInterno(new SituacaoTransporte());
  }//GEN-LAST:event_abreSituacaoTransporte

  private void abreSimulacao(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abreSimulacao
		mostraFrameInterno(new LeituraSimulacao());
  }//GEN-LAST:event_abreSimulacao

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuItem carregarDadosMenuItem;
  private javax.swing.JDesktopPane desktopPane;
  private javax.swing.JMenu menuArquivo;
  private javax.swing.JMenuBar menuBar;
  private javax.swing.JMenu menuGeral;
  private javax.swing.JMenu menuRelatorio;
  private javax.swing.JMenuItem novoDroneMenuItem;
  private javax.swing.JMenuItem novoTransporteMenuItem;
  private javax.swing.JMenuItem processarTransporteMenuItem;
  private javax.swing.JMenuItem relatorioGeralMenuItem;
  private javax.swing.JMenuItem relatorioTransportesMenuItem;
  private javax.swing.JMenuItem sairMenuItem;
  private javax.swing.JMenuItem salvarDadosMenuItem;
  private javax.swing.JPopupMenu.Separator separadorMenuGeral1;
  private javax.swing.JPopupMenu.Separator separadorMenuGeral2;
  private javax.swing.JPopupMenu.Separator separatorMenuArquivo1;
  private javax.swing.JMenuItem simulacaoMenuItem;
  private javax.swing.JMenuItem situacaoTransporteMenuItem;
  // End of variables declaration//GEN-END:variables
}
