package views;

import dados.Transporte;
import dados.TransporteCargaInanimada;
import dados.TransporteCargaViva;
import dados.TransportePessoal;
import handlers.TransporteHandler;

import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFormattedTextField;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.ActionEvent;

/**
 * {@link JInternalFrame} que contém o formulário para
 * o cadastro de novas instâncias de {@link Transporte}
 * no sistema.
 *
 * @author Lucas da Paz
 */
public class CadastroTransporte extends javax.swing.JInternalFrame {
	private final TransporteHandler transporteHandler;

	/**
	 * Inicializa um novo frame {@link CadastroTransporte}.
	 */
	public CadastroTransporte() {
		transporteHandler = TransporteHandler.getHandler();
		initComponents();
	}

	/**
	 * Limpa todos os campos de texto e caixas de seleção
	 * do formulário.
	 */
	private void limpaCampos() {
		inputNumero.setText("");
		inputPeso.setText("");
		inputCliente.setText("");
		inputDescricao.setText("");
		inputLatOrigem.setText("");
		inputLongOrigem.setText("");
		inputLatDestino.setText("");
		inputLongDestino.setText("");
		inputQtdPessoasPessoal.setText("");
		inputTemperaturaMinimaCargaViva.setText("");
		inputTemperaturaMaximaCargaViva.setText("");
		checkPerigosaCargaInanimada.setSelected(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    JPanel painelHeader = new JPanel();
    JLabel title = new JLabel();
    JPanel painelGeral = new JPanel();
    JLabel labelNumero = new JLabel();
    inputNumero = new JFormattedTextField(Constantes.FORMATO_INTEIRO);
    JLabel labelPeso = new JLabel();
    inputPeso = new JFormattedTextField(Constantes.FORMATO_PONTO_FLUTUANTE);
    JLabel labelCliente = new JLabel();
    inputCliente = new JTextField();
    JLabel labelDescricao = new JLabel();
    inputDescricao = new JTextField();
    JPanel PainelCoordenadas = new JPanel();
    JLabel labelLatOrigem = new JLabel();
    inputLatOrigem = new JFormattedTextField(Constantes.FORMATO_PONTO_FLUTUANTE);
    JLabel labelLongOrigem = new JLabel();
    inputLongOrigem = new JFormattedTextField(Constantes.FORMATO_PONTO_FLUTUANTE);
    JLabel labelLatDestino = new JLabel();
    inputLatDestino = new JFormattedTextField(Constantes.FORMATO_PONTO_FLUTUANTE);
    JLabel labelLongDestino = new JLabel();
    inputLongDestino = new JFormattedTextField(Constantes.FORMATO_PONTO_FLUTUANTE);
    painelAbas = new JTabbedPane();
    JPanel tabTransportePessoal = new JPanel();
    JLabel labelQtdPessoasPessoal = new JLabel();
    inputQtdPessoasPessoal = new JFormattedTextField(Constantes.FORMATO_INTEIRO);
    JPanel tabCargaInanimada = new JPanel();
    checkPerigosaCargaInanimada = new JCheckBox();
    JPanel tabCargaViva = new JPanel();
    JLabel labelTemperaturaMinimaCargaViva = new JLabel();
    inputTemperaturaMinimaCargaViva = new JFormattedTextField(Constantes.FORMATO_PONTO_FLUTUANTE);
    JLabel labelTemperaturaMaximaCargaViva = new JLabel();
    inputTemperaturaMaximaCargaViva = new JFormattedTextField(Constantes.FORMATO_PONTO_FLUTUANTE);
    JPanel painelBotoes = new JPanel();
    JButton btnCadastrar = new JButton();
    JButton btnLimpar = new JButton();

    setClosable(true);
    setIconifiable(true);
    setMaximizable(true);
    setResizable(true);
    setTitle("Cadastro de Transporte");
    setPreferredSize(new Dimension(550, 650));
    setVisible(true);

    title.setFont(Constantes.FONTE_TITULO);
    title.setHorizontalAlignment(SwingConstants.CENTER);
    title.setLabelFor(this);
    title.setText(getTitle());
    title.setPreferredSize(new Dimension(70, 25));

    GroupLayout painelHeaderLayout = new GroupLayout(painelHeader);
    painelHeader.setLayout(painelHeaderLayout);
    painelHeaderLayout.setHorizontalGroup(painelHeaderLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(GroupLayout.Alignment.TRAILING, painelHeaderLayout.createSequentialGroup()
        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(title, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    painelHeaderLayout.setVerticalGroup(painelHeaderLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(painelHeaderLayout.createSequentialGroup()
        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(title, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    painelGeral.setBorder(BorderFactory.createTitledBorder("Informações gerais"));

    labelNumero.setLabelFor(inputNumero);
    labelNumero.setText("Número:");
    labelNumero.setPreferredSize(new Dimension(125, 15));

    inputNumero.setToolTipText("Informe o número do transporte");
    inputNumero.setPreferredSize(new Dimension(125, 30));

    labelPeso.setLabelFor(inputPeso);
    labelPeso.setText("Peso:");
    labelPeso.setPreferredSize(new Dimension(125, 15));

    inputPeso.setToolTipText("Informe o peso do transporte em Kg");
    inputPeso.setPreferredSize(new Dimension(125, 30));

    labelCliente.setLabelFor(inputCliente);
    labelCliente.setText("Cliente:");
    labelCliente.setPreferredSize(new Dimension(125, 15));

    inputCliente.setToolTipText("Informe o nome do cliente");
    inputCliente.setPreferredSize(new Dimension(125, 30));

    labelDescricao.setLabelFor(inputDescricao);
    labelDescricao.setText("Descrição:");
    labelDescricao.setPreferredSize(new Dimension(125, 15));

    inputDescricao.setToolTipText("Descreva brevemente o transporte");
    inputDescricao.setPreferredSize(new Dimension(125, 30));

    GroupLayout painelGeralLayout = new GroupLayout(painelGeral);
    painelGeral.setLayout(painelGeralLayout);
    painelGeralLayout.setHorizontalGroup(painelGeralLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(painelGeralLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(painelGeralLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
          .addGroup(painelGeralLayout.createSequentialGroup()
            .addGroup(painelGeralLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
              .addComponent(inputNumero, GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
              .addComponent(labelNumero, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelGeralLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
              .addComponent(inputPeso, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(labelPeso, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelGeralLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
              .addComponent(labelCliente, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
              .addComponent(inputCliente, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
          .addComponent(labelDescricao, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(inputDescricao, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    painelGeralLayout.setVerticalGroup(painelGeralLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(painelGeralLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(painelGeralLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
          .addGroup(painelGeralLayout.createSequentialGroup()
            .addComponent(labelPeso, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(inputPeso, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
          .addGroup(painelGeralLayout.createSequentialGroup()
            .addGroup(painelGeralLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
              .addComponent(labelCliente, GroupLayout.Alignment.LEADING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
              .addComponent(labelNumero, GroupLayout.Alignment.LEADING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(painelGeralLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
              .addComponent(inputNumero, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
              .addComponent(inputCliente, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(labelDescricao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(inputDescricao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    inputCliente.getAccessibleContext().setAccessibleName("");

    PainelCoordenadas.setBorder(BorderFactory.createTitledBorder("Coordenadas"));

    labelLatOrigem.setLabelFor(inputLatOrigem);
    labelLatOrigem.setText("Latitude origem:");
    labelLatOrigem.setPreferredSize(new Dimension(200, 15));

    inputLatOrigem.setToolTipText("Informe a latitude de origem em graus");
    inputLatOrigem.setPreferredSize(new Dimension(200, 30));

    labelLongOrigem.setLabelFor(inputLongOrigem);
    labelLongOrigem.setText("Longitude origem:");
    labelLongOrigem.setPreferredSize(new Dimension(200, 15));

    inputLongOrigem.setToolTipText("Informe a longitude de origem em graus");
    inputLongOrigem.setPreferredSize(new Dimension(200, 30));

    labelLatDestino.setLabelFor(inputLatDestino);
    labelLatDestino.setText("Latitude destino:");
    labelLatDestino.setPreferredSize(new Dimension(200, 15));

    inputLatDestino.setToolTipText("Informe a latitude de destino em graus");
    inputLatDestino.setPreferredSize(new Dimension(200, 30));

    labelLongDestino.setLabelFor(inputLongDestino);
    labelLongDestino.setText("Longitude destino:");
    labelLongDestino.setPreferredSize(new Dimension(200, 15));

    inputLongDestino.setToolTipText("Informe a longitude de destino em graus");
    inputLongDestino.setPreferredSize(new Dimension(200, 30));

    GroupLayout PainelCoordenadasLayout = new GroupLayout(PainelCoordenadas);
    PainelCoordenadas.setLayout(PainelCoordenadasLayout);
    PainelCoordenadasLayout.setHorizontalGroup(PainelCoordenadasLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(PainelCoordenadasLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(PainelCoordenadasLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
          .addGroup(PainelCoordenadasLayout.createSequentialGroup()
            .addGroup(PainelCoordenadasLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
              .addComponent(inputLatOrigem, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(labelLatOrigem, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PainelCoordenadasLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
              .addComponent(inputLongOrigem, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(labelLongOrigem, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)))
          .addGroup(PainelCoordenadasLayout.createSequentialGroup()
            .addGroup(PainelCoordenadasLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
              .addComponent(inputLatDestino, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(labelLatDestino, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PainelCoordenadasLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
              .addComponent(inputLongDestino, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(labelLongDestino, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE))))
        .addContainerGap())
    );
    PainelCoordenadasLayout.setVerticalGroup(PainelCoordenadasLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(PainelCoordenadasLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(PainelCoordenadasLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
          .addGroup(PainelCoordenadasLayout.createSequentialGroup()
            .addComponent(labelLongOrigem, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(inputLongOrigem, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
          .addGroup(PainelCoordenadasLayout.createSequentialGroup()
            .addComponent(labelLatOrigem, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(inputLatOrigem, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(PainelCoordenadasLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
          .addGroup(PainelCoordenadasLayout.createSequentialGroup()
            .addComponent(labelLatDestino, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(inputLatDestino, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
          .addGroup(PainelCoordenadasLayout.createSequentialGroup()
            .addComponent(labelLongDestino, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(inputLongDestino, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );

    painelAbas.setToolTipText("Escolha o tipo de transporte que será cadastrado e preencha as informações");

    labelQtdPessoasPessoal.setLabelFor(inputQtdPessoasPessoal);
    labelQtdPessoasPessoal.setText("Quantidade de pessoas:");
    labelQtdPessoasPessoal.setPreferredSize(new Dimension(125, 15));

    inputQtdPessoasPessoal.setToolTipText("Informe a quantidade de pessoas que será transportada");
    inputQtdPessoasPessoal.setPreferredSize(new Dimension(125, 30));

    GroupLayout tabTransportePessoalLayout = new GroupLayout(tabTransportePessoal);
    tabTransportePessoal.setLayout(tabTransportePessoalLayout);
    tabTransportePessoalLayout.setHorizontalGroup(tabTransportePessoalLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(tabTransportePessoalLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(tabTransportePessoalLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
          .addComponent(labelQtdPessoasPessoal, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(inputQtdPessoasPessoal, GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
        .addContainerGap(390, Short.MAX_VALUE))
    );
    tabTransportePessoalLayout.setVerticalGroup(tabTransportePessoalLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(tabTransportePessoalLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(labelQtdPessoasPessoal, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(inputQtdPessoasPessoal, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    painelAbas.addTab("Pessoal", tabTransportePessoal);

    checkPerigosaCargaInanimada.setText("Carga perigosa");
    checkPerigosaCargaInanimada.setToolTipText("Marque a caixa de seleção se a carga é perigosa");

    GroupLayout tabCargaInanimadaLayout = new GroupLayout(tabCargaInanimada);
    tabCargaInanimada.setLayout(tabCargaInanimadaLayout);
    tabCargaInanimadaLayout.setHorizontalGroup(tabCargaInanimadaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(tabCargaInanimadaLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(checkPerigosaCargaInanimada)
        .addContainerGap(414, Short.MAX_VALUE))
    );
    tabCargaInanimadaLayout.setVerticalGroup(tabCargaInanimadaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(tabCargaInanimadaLayout.createSequentialGroup()
        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(checkPerigosaCargaInanimada)
        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    painelAbas.addTab("Carga Inanimada", tabCargaInanimada);

    labelTemperaturaMinimaCargaViva.setLabelFor(inputTemperaturaMinimaCargaViva);
    labelTemperaturaMinimaCargaViva.setText("Temperatura mínima:");
    labelTemperaturaMinimaCargaViva.setPreferredSize(new Dimension(140, 15));

    inputTemperaturaMinimaCargaViva.setToolTipText("Informe a temperatura mínima do transporte em graus Celsius");
    inputTemperaturaMinimaCargaViva.setPreferredSize(new Dimension(140, 30));

    labelTemperaturaMaximaCargaViva.setLabelFor(inputTemperaturaMaximaCargaViva);
    labelTemperaturaMaximaCargaViva.setText("Temperatura máxima:");
    labelTemperaturaMaximaCargaViva.setPreferredSize(new Dimension(140, 15));

    inputTemperaturaMaximaCargaViva.setToolTipText("Informe a temperatura máxima do transporte em graus Celsius");
    inputTemperaturaMaximaCargaViva.setPreferredSize(new Dimension(140, 30));

    GroupLayout tabCargaVivaLayout = new GroupLayout(tabCargaViva);
    tabCargaViva.setLayout(tabCargaVivaLayout);
    tabCargaVivaLayout.setHorizontalGroup(tabCargaVivaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(tabCargaVivaLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(tabCargaVivaLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
          .addComponent(inputTemperaturaMinimaCargaViva, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(labelTemperaturaMinimaCargaViva, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(tabCargaVivaLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
          .addComponent(labelTemperaturaMaximaCargaViva, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(inputTemperaturaMaximaCargaViva, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(228, Short.MAX_VALUE))
    );
    tabCargaVivaLayout.setVerticalGroup(tabCargaVivaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(tabCargaVivaLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(tabCargaVivaLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
          .addGroup(tabCargaVivaLayout.createSequentialGroup()
            .addComponent(labelTemperaturaMaximaCargaViva, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(inputTemperaturaMaximaCargaViva, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
          .addGroup(tabCargaVivaLayout.createSequentialGroup()
            .addComponent(labelTemperaturaMinimaCargaViva, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(inputTemperaturaMinimaCargaViva, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );

    painelAbas.addTab("Carga Viva", tabCargaViva);

    btnCadastrar.setText("Cadastrar");
    btnCadastrar.setToolTipText("Cadastrar novo transporte");
    btnCadastrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    btnCadastrar.setPreferredSize(new Dimension(95, 30));
    getRootPane().setDefaultButton(btnCadastrar);
    btnCadastrar.addActionListener(this::cadastraTransporte);

    btnLimpar.setText("Limpar");
    btnLimpar.setToolTipText("Limpar os campos do formulário");
    btnLimpar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    btnLimpar.setPreferredSize(new Dimension(95, 30));
    btnLimpar.addActionListener(this::chamaLimpaCampos);

    GroupLayout painelBotoesLayout = new GroupLayout(painelBotoes);
    painelBotoes.setLayout(painelBotoesLayout);
    painelBotoesLayout.setHorizontalGroup(painelBotoesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(painelBotoesLayout.createSequentialGroup()
        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnCadastrar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnLimpar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    painelBotoesLayout.setVerticalGroup(painelBotoesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(painelBotoesLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(painelBotoesLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
          .addComponent(btnCadastrar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
          .addComponent(btnLimpar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    GroupLayout layout = new GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addComponent(painelHeader, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
          .addComponent(painelGeral, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(painelAbas)
          .addComponent(painelBotoes, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(PainelCoordenadas, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(20, Short.MAX_VALUE)
        .addComponent(painelHeader, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(painelGeral, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(PainelCoordenadas, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(painelAbas, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(painelBotoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        .addContainerGap(35, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

	/**
	 * Valida os campos e cria um novo {@link Transporte} com
	 * o número passado como argumento.
	 *
	 * @param numero O número do transporte que será criado.
	 * @return O transporte instanciado, ou {@code null} se alguma
	 * das validações realizadas falhar.
	 */
	private Transporte criaTransporte(int numero) {
		double peso = Double.parseDouble(inputPeso.getText());
		if (peso <= 0) {
			JOptionPane.showMessageDialog(this, "O peso do transporte deve ser maior do que zero!", getTitle(), JOptionPane.WARNING_MESSAGE);
			return null;
		}

		String cliente = inputCliente.getText();
		if (cliente.isEmpty()) {
			JOptionPane.showMessageDialog(this, "O nome do cliente deve ser informado!", getTitle(), JOptionPane.WARNING_MESSAGE);
			return null;
		}

		String descricao = inputDescricao.getText();
		if (descricao.isEmpty()) {
			JOptionPane.showMessageDialog(this, "A descrição do transporte deve ser preenchida!", getTitle(), JOptionPane.WARNING_MESSAGE);
			return null;
		}

		double latitudeOrigem = Double.parseDouble(inputLatOrigem.getText());
		double longitudeOrigem = Double.parseDouble(inputLongOrigem.getText());
		double latitudeDestino = Double.parseDouble(inputLatDestino.getText());
		double longitudeDestino = Double.parseDouble(inputLongDestino.getText());

		if (latitudeOrigem == latitudeDestino && longitudeOrigem == longitudeDestino) {
			JOptionPane.showMessageDialog(this, "As coordenadas de origem e de destino devem ser diferentes!", getTitle(), JOptionPane.WARNING_MESSAGE);
			return null;
		}

		int tipoTransporte = painelAbas.getSelectedIndex();
		return switch (tipoTransporte) {
			case 0 ->
				criaTransportePessoal(numero, cliente, descricao, peso, latitudeOrigem, longitudeOrigem, latitudeDestino, longitudeDestino);
			case 1 ->
				criaTransporteCargaInanimada(numero, cliente, descricao, peso, latitudeOrigem, longitudeOrigem, latitudeDestino, longitudeDestino);
			case 2 ->
				criaTransporteCargaViva(numero, cliente, descricao, peso, latitudeOrigem, longitudeOrigem, latitudeDestino, longitudeDestino);
			default ->
				null;
		};
	}

	/**
	 * Lê os campos necessários, realiza as validações e cria uma
	 * nova instância de {@link TransportePessoal} com os valores
	 * passados como argumento.
	 *
	 * @param numero           O número do transporte.
	 * @param cliente          O nome do cliente relacionado.
	 * @param descricao        A descrição do transporte.
	 * @param peso             O peso do transporte, em kg.
	 * @param latitudeOrigem   A latitude de origem do transporte, em graus.
	 * @param longitudeOrigem  A longitude de origem do transporte, em graus.
	 * @param latitudeDestino  A latitude de destino do transporte, em graus.
	 * @param longitudeDestino A longitude de destino do transporte, em graus.
	 * @return O transporte instanciado, ou {@code null} se alguma das
	 * validações realizadas falhar.
	 */
	private Transporte criaTransportePessoal(int numero, String cliente, String descricao, double peso,
		double latitudeOrigem, double longitudeOrigem, double latitudeDestino, double longitudeDestino) {
		int qtdPessoas = Integer.parseInt(inputQtdPessoasPessoal.getText());
		if (qtdPessoas < 0) {
			JOptionPane.showMessageDialog(this, "O campo \"Quantidade de pessoas\" não pode ser negativo!", getTitle(), JOptionPane.WARNING_MESSAGE);
			return null;
		}

		return new TransportePessoal(numero, cliente, descricao, peso, latitudeOrigem,  longitudeOrigem,  latitudeDestino,  longitudeDestino, qtdPessoas);
	}

	/**
	 * Lê os campos necessários, realiza as validações e cria uma
	 * nova instância de {@link TransporteCargaInanimada} com os
	 * valores passados como argumento.
	 *
	 * @param numero           O número do transporte.
	 * @param cliente          O nome do cliente relacionado.
	 * @param descricao        A descrição do transporte.
	 * @param peso             O peso do transporte, em kg.
	 * @param latitudeOrigem   A latitude de origem do transporte, em graus.
	 * @param longitudeOrigem  A longitude de origem do transporte, em graus.
	 * @param latitudeDestino  A latitude de destino do transporte, em graus.
	 * @param longitudeDestino A longitude de destino do transporte, em graus.
	 * @return O transporte instanciado, ou {@code null} se alguma das
	 * validações realizadas falhar.
	 */
	private Transporte criaTransporteCargaInanimada(int numero, String cliente, String descricao, double peso,
		double latitudeOrigem, double longitudeOrigem, double latitudeDestino, double longitudeDestino) {
		boolean cargaPerigosa = checkPerigosaCargaInanimada.isSelected();
		return new TransporteCargaInanimada(numero, cliente, descricao, peso, latitudeOrigem,  longitudeOrigem,  latitudeDestino,  longitudeDestino, cargaPerigosa);
	}

	/**
	 * Lê os campos necessários, realiza as validações e cria uma
	 * nova instância de {@link TransporteCargaViva} com os valores
	 * passados como argumento.
	 *
	 * @param numero           O número do transporte.
	 * @param cliente          O nome do cliente relacionado.
	 * @param descricao        A descrição do transporte.
	 * @param peso             O peso do transporte, em kg.
	 * @param latitudeOrigem   A latitude de origem do transporte, em graus.
	 * @param longitudeOrigem  A longitude de origem do transporte, em graus.
	 * @param latitudeDestino  A latitude de destino do transporte, em graus.
	 * @param longitudeDestino A longitude de destino do transporte, em graus.
	 * @return O transporte instanciado, ou {@code null} se alguma das
	 * validações realizadas falhar.
	 */
	private Transporte criaTransporteCargaViva(int numero, String cliente, String descricao, double peso,
		double latitudeOrigem, double longitudeOrigem, double latitudeDestino, double longitudeDestino) {
		double temperaturaMinima = Double.parseDouble(inputTemperaturaMinimaCargaViva.getText());
		double temperaturaMaxima = Double.parseDouble(inputTemperaturaMaximaCargaViva.getText());

		if (temperaturaMaxima < temperaturaMinima) {
			JOptionPane.showMessageDialog(this, "A temperatura mínima não pode ser maior do que a temperatura máxima!", getTitle(), JOptionPane.WARNING_MESSAGE);
			return null;
		}

		return new TransporteCargaViva(numero, cliente, descricao, peso, latitudeOrigem,  longitudeOrigem,  latitudeDestino,  longitudeDestino, temperaturaMinima, temperaturaMaxima);
	}

  private void cadastraTransporte(ActionEvent evt) {//GEN-FIRST:event_cadastraTransporte
		try {
			int numero = Integer.parseInt(inputNumero.getText());
			if (numero <= 0) {
				JOptionPane.showMessageDialog(this, "O número do transporte deve ser um inteiro positivo!", getTitle(), JOptionPane.WARNING_MESSAGE);
				return;
			}

			Transporte novoTransporte = criaTransporte(numero);
			if (novoTransporte == null) {
				return;
			}

			String[] opcoes = {"Sim", "Não"};
			int resposta = JOptionPane.showOptionDialog(this,
				"%s\n\nConfirma a criação do transporte?".formatted(novoTransporte),
				getTitle(), JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[1]);

			if (resposta != 0) {
				return;
			}

			boolean sucesso = transporteHandler.cadastra(novoTransporte);
			if (!sucesso) {
				JOptionPane.showMessageDialog(this, "Já existe um transporte cadastrado com o número %d".formatted(numero),
					getTitle(), JOptionPane.WARNING_MESSAGE);
				return;
			}

			JOptionPane.showMessageDialog(this, "Transporte cadastrado com sucesso!",
				getTitle(), JOptionPane.INFORMATION_MESSAGE);
			limpaCampos();
		} catch (Exception e) {
			e.printStackTrace(System.err);
			JOptionPane.showMessageDialog(this, "Erro ao cadastrar transporte...\nVerifique o tipo de transporte e se os campos estão preenchidos corretamente!", getTitle(), JOptionPane.ERROR_MESSAGE);
		}
  }//GEN-LAST:event_cadastraTransporte

	private void chamaLimpaCampos(ActionEvent evt) {//GEN-FIRST:event_chamaLimpaCampos
		limpaCampos();
  }//GEN-LAST:event_chamaLimpaCampos

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JCheckBox checkPerigosaCargaInanimada;
  private JTextField inputCliente;
  private JTextField inputDescricao;
  private JFormattedTextField inputLatDestino;
  private JFormattedTextField inputLatOrigem;
  private JFormattedTextField inputLongDestino;
  private JFormattedTextField inputLongOrigem;
  private JFormattedTextField inputNumero;
  private JFormattedTextField inputPeso;
  private JFormattedTextField inputQtdPessoasPessoal;
  private JFormattedTextField inputTemperaturaMaximaCargaViva;
  private JFormattedTextField inputTemperaturaMinimaCargaViva;
  private JTabbedPane painelAbas;
  // End of variables declaration//GEN-END:variables
}
