package views;

import handlers.DroneHandler;
import handlers.TransporteHandler;

import javax.swing.JOptionPane;

/**
 *
 * @author Lucas da Paz
 */
public class ProcessamentoTransportes extends javax.swing.JInternalFrame {
	private final DroneHandler droneHandler;
	private final TransporteHandler transporteHandler;

	public ProcessamentoTransportes() {
		droneHandler = DroneHandler.getHandler();
		transporteHandler = TransporteHandler.getHandler();
		initComponents();
		mostraTotalPendentes();
	}

	private void mostraTotalPendentes() {
		int qtdPendentes = transporteHandler.getTotalPendentes();
		StringBuilder textoRegistro = new StringBuilder();
		textoRegistro.append(qtdPendentes == 0 ? "Nenhum" : qtdPendentes);
		textoRegistro.append(qtdPendentes <= 1 ? " transporte pendente" : " transportes pendentes");
		textoRegistro.append("!\n");

		textAreaRegistro.append(textoRegistro.toString());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    painelHeader = new javax.swing.JPanel();
    title = new javax.swing.JLabel();
    painelRegistro = new javax.swing.JPanel();
    scrollPaneRegistro = new javax.swing.JScrollPane();
    textAreaRegistro = new javax.swing.JTextArea();
    painelBotoes = new javax.swing.JPanel();
    btnProcessar = new javax.swing.JButton();
    btnLimpar = new javax.swing.JButton();

    setClosable(true);
    setIconifiable(true);
    setMaximizable(true);
    setResizable(true);
    setTitle("Processamento de Transportes Pendentes");
    setVisible(true);

    title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    title.setLabelFor(this);
    title.setText(getTitle());

    javax.swing.GroupLayout painelHeaderLayout = new javax.swing.GroupLayout(painelHeader);
    painelHeader.setLayout(painelHeaderLayout);
    painelHeaderLayout.setHorizontalGroup(
      painelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelHeaderLayout.createSequentialGroup()
        .addContainerGap(109, Short.MAX_VALUE)
        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
        .addContainerGap(111, Short.MAX_VALUE))
    );
    painelHeaderLayout.setVerticalGroup(
      painelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(painelHeaderLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(title)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    painelRegistro.setBorder(javax.swing.BorderFactory.createTitledBorder("Registros"));
    painelRegistro.setPreferredSize(new java.awt.Dimension(500, 225));

    textAreaRegistro.setEditable(false);
    textAreaRegistro.setColumns(20);
    textAreaRegistro.setLineWrap(true);
    textAreaRegistro.setRows(5);
    textAreaRegistro.setTabSize(2);
    textAreaRegistro.setToolTipText("Registros do processamento de transportes pendentes");
    scrollPaneRegistro.setViewportView(textAreaRegistro);

    javax.swing.GroupLayout painelRegistroLayout = new javax.swing.GroupLayout(painelRegistro);
    painelRegistro.setLayout(painelRegistroLayout);
    painelRegistroLayout.setHorizontalGroup(
      painelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(scrollPaneRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
    );
    painelRegistroLayout.setVerticalGroup(
      painelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(scrollPaneRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
    );

    btnProcessar.setText("Processar");
    btnProcessar.setToolTipText("Realizar o processamento dos transportes pendentes");
    btnProcessar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnProcessar.setPreferredSize(new java.awt.Dimension(95, 30));
    getRootPane().setDefaultButton(btnProcessar);
    btnProcessar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        processaTransportesPendentes(evt);
      }
    });

    btnLimpar.setText("Limpar");
    btnLimpar.setToolTipText("Limpar campo de registros do processamento");
    btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnLimpar.setPreferredSize(new java.awt.Dimension(95, 30));
    btnLimpar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        limpaRegistros(evt);
      }
    });

    javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
    painelBotoes.setLayout(painelBotoesLayout);
    painelBotoesLayout.setHorizontalGroup(
      painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(painelBotoesLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnProcessar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    painelBotoesLayout.setVerticalGroup(
      painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(painelBotoesLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnProcessar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(painelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(painelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(painelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(20, Short.MAX_VALUE)
        .addComponent(painelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(painelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(35, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void limpaRegistros(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpaRegistros
		textAreaRegistro.setText("");
  }//GEN-LAST:event_limpaRegistros

  private void processaTransportesPendentes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processaTransportesPendentes
		int pendentesAntes = transporteHandler.getTotalPendentes();
		boolean processado = transporteHandler.processaPendentes(droneHandler.buscaTodos());

		if (!processado) {
			String mensagem = "Processamento não realizado:\nNão há transportes pendentes!";
			textAreaRegistro.append("\n%s\n".formatted(mensagem));
			JOptionPane.showMessageDialog(this, mensagem, getTitle(), JOptionPane.INFORMATION_MESSAGE);
			return;
		}

		String separador = "%75s".formatted(" ").replace(" ", "-");
		StringBuilder registro = new StringBuilder(separador);
		registro.append("\n- Resultado do processamento -\n\n");

		int pendentesDepois = transporteHandler.getTotalPendentes();
		String alocados = "Transportes alocados: %d\n".formatted(pendentesAntes - pendentesDepois);

		registro.append("* Transportes pendentes antes do processamento: %d\n".formatted(pendentesAntes));
		registro.append("* ").append(alocados);
		registro.append("* Total de transportes pendentes: %d\n".formatted(pendentesDepois));
		registro.append(separador).append("\n");

		textAreaRegistro.append(registro.toString());
		JOptionPane.showMessageDialog(this, "Processamento concluído!\n%s".formatted(alocados), getTitle(), JOptionPane.INFORMATION_MESSAGE);
		mostraTotalPendentes();
  }//GEN-LAST:event_processaTransportesPendentes


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnLimpar;
  private javax.swing.JButton btnProcessar;
  private javax.swing.JPanel painelBotoes;
  private javax.swing.JPanel painelHeader;
  private javax.swing.JPanel painelRegistro;
  private javax.swing.JScrollPane scrollPaneRegistro;
  private javax.swing.JTextArea textAreaRegistro;
  private javax.swing.JLabel title;
  // End of variables declaration//GEN-END:variables
}
