package views;

import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.ActionEvent;

/**
 * Classe abstrata que serve para encapsular o {@link JInternalFrame}
 * que contém o formulário utilizado para gerar relatórios.
 *
 * @author Lucas da Paz
 */
public abstract class Relatorio extends javax.swing.JInternalFrame {
	private final String titulo;

  /**
   * Inicializa um novo frame {@link Relatorio}.
   */
	public Relatorio(String titulo) {
		this.titulo = titulo;
		initComponents();
	}

  /**
   * @return Relatório que deve ser exibido na área de texto.
   */
	protected abstract String geraRelatorio();

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    JPanel painelHeader = new JPanel();
    JLabel title = new JLabel();
    JPanel painelRelatorio = new JPanel();
    JScrollPane scrollPaneRelatorio = new JScrollPane();
    textAreaRelatorio = new JTextArea();
    JPanel painelBotoes = new JPanel();
    JButton btnGerar = new JButton();
    JButton btnCopiar = new JButton();

    setClosable(true);
    setIconifiable(true);
    setMaximizable(true);
    setResizable(true);
    setTitle(titulo);
    setPreferredSize(new Dimension(550, 600));
    setVisible(true);

    title.setFont(Constantes.FONTE_TITULO);
    title.setHorizontalAlignment(SwingConstants.CENTER);
    title.setLabelFor(this);
    title.setText(getTitle());

    GroupLayout painelHeaderLayout = new GroupLayout(painelHeader);
    painelHeader.setLayout(painelHeaderLayout);
    painelHeaderLayout.setHorizontalGroup(painelHeaderLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(GroupLayout.Alignment.TRAILING, painelHeaderLayout.createSequentialGroup()
        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(title, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    painelHeaderLayout.setVerticalGroup(painelHeaderLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(painelHeaderLayout.createSequentialGroup()
        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(title, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    painelRelatorio.setBorder(BorderFactory.createTitledBorder("Relatório"));
    painelRelatorio.setPreferredSize(new Dimension(500, 400));

    scrollPaneRelatorio.setPreferredSize(new Dimension(500, 400));

    textAreaRelatorio.setEditable(false);
    textAreaRelatorio.setColumns(20);
    textAreaRelatorio.setLineWrap(true);
    textAreaRelatorio.setRows(5);
    textAreaRelatorio.setTabSize(2);
    textAreaRelatorio.setWrapStyleWord(true);
    scrollPaneRelatorio.setViewportView(textAreaRelatorio);

    GroupLayout painelRelatorioLayout = new GroupLayout(painelRelatorio);
    painelRelatorio.setLayout(painelRelatorioLayout);
    painelRelatorioLayout.setHorizontalGroup(painelRelatorioLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addComponent(scrollPaneRelatorio, GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
    );
    painelRelatorioLayout.setVerticalGroup(painelRelatorioLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addComponent(scrollPaneRelatorio, GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
    );

    btnGerar.setText("Gerar");
    btnGerar.setToolTipText("Gerar um novo relatório");
    btnGerar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    btnGerar.setPreferredSize(new Dimension(95, 30));
    getRootPane().setDefaultButton(btnGerar);
    btnGerar.addActionListener(this::mostraRelatorio);

    btnCopiar.setText("Copiar");
    btnCopiar.setToolTipText("Limpar relatório");
    btnCopiar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    btnCopiar.setPreferredSize(new Dimension(95, 30));
    btnCopiar.addActionListener(this::copiaRelatorio);

    GroupLayout painelBotoesLayout = new GroupLayout(painelBotoes);
    painelBotoes.setLayout(painelBotoesLayout);
    painelBotoesLayout.setHorizontalGroup(painelBotoesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(painelBotoesLayout.createSequentialGroup()
        .addContainerGap(103, Short.MAX_VALUE)
        .addComponent(btnGerar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
        .addComponent(btnCopiar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        .addContainerGap(104, Short.MAX_VALUE))
    );
    painelBotoesLayout.setVerticalGroup(painelBotoesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(painelBotoesLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(painelBotoesLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
          .addComponent(btnGerar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
          .addComponent(btnCopiar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    GroupLayout layout = new GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addComponent(painelHeader, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(26, Short.MAX_VALUE)
        .addComponent(painelRelatorio, GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        .addContainerGap(27, Short.MAX_VALUE))
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(painelBotoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(22, Short.MAX_VALUE)
        .addComponent(painelHeader, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(painelRelatorio, GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        .addGap(18, 18, 18)
        .addComponent(painelBotoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        .addContainerGap(35, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void copiaRelatorio(ActionEvent evt) {//GEN-FIRST:event_copiaRelatorio
		StringSelection selecao = new StringSelection(textAreaRelatorio.getText());
    Clipboard areaDeTransferencia = Toolkit.getDefaultToolkit().getSystemClipboard();
    areaDeTransferencia.setContents(selecao, null);
  }//GEN-LAST:event_copiaRelatorio

  private void mostraRelatorio(ActionEvent evt) {//GEN-FIRST:event_mostraRelatorio
		textAreaRelatorio.setText("\n%s\n".formatted(geraRelatorio()));
		textAreaRelatorio.setCaretPosition(0);
  }//GEN-LAST:event_mostraRelatorio

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JTextArea textAreaRelatorio;
  // End of variables declaration//GEN-END:variables
}
