package views;

import dados.Estado;
import dados.Transporte;
import handlers.TransporteHandler;

import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.util.List;

/**
 * {@link JInternalFrame} que contém o formulário utilizado
 * para buscar e alterar a situação de determinado {@link Transporte}.
 *
 * @author Lucas da Paz
 */
public class SituacaoTransporte extends javax.swing.JInternalFrame {
	private final TransporteHandler transporteHandler;
	private Transporte transporte;

	/**
	 * Inicializa um novo frame {@link SituacaoTransporte}.
	 */
	public SituacaoTransporte() {
		transporteHandler = TransporteHandler.getHandler();
		initComponents();
	}

	/**
	 * Habilita o painel de escolha de situação do {@link Transporte}.
	 */
	private void ativaPainelSituacao() {
		List<Estado> estados = switch (transporte.getSituacao()) {
			case PENDENTE -> List.of(Estado.CANCELADO);
			case ALOCADO -> List.of(Estado.TERMINADO, Estado.CANCELADO);
			default -> null;
		};

		if (estados == null) {
			JOptionPane.showMessageDialog(this,
				"O transporte de número %d já foi finalizado e não pode ter sua situação alterada".formatted(transporte.getNumero()),
				getTitle(), JOptionPane.INFORMATION_MESSAGE);
			return;
		}

		comboSituacao.setModel(new DefaultComboBoxModel<>(estados.toArray(Estado[]::new)));
		comboSituacao.setEnabled(true);
		btnDefinir.setEnabled(true);
	}

	/**
	 * Desabilita o painel de escolha de situação do {@link Transporte}.
	 */
	private void desativaPainelSituacao() {
		comboSituacao.setSelectedIndex(-1);
		comboSituacao.setEnabled(false);
		btnDefinir.setEnabled(false);
	}

	/**
	 * Mostra as informações do {@link Transporte} buscado na
	 * área de texto.
	 */
	private void mostraTransporte() {
		textAreaTransporte.setText(transporte.toString());
		if (transporte.getDrone() != null) {
			textAreaTransporte.append("\n> Transportador -> %s".formatted(transporte.getDrone()));
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    JPanel painelHeader = new JPanel();
    JLabel title = new JLabel();
    JPanel painelLocalizar = new JPanel();
    JLabel labelNumero = new JLabel();
    inputNumero = new JFormattedTextField(Constantes.FORMATO_INTEIRO);
    JButton btnBuscar = new JButton();
    JLabel labelTransporte = new JLabel();
    JScrollPane scrollPaneTransporte = new JScrollPane();
    textAreaTransporte = new JTextArea();
    JPanel painelSituacao = new JPanel();
    JLabel labelSituacao = new JLabel();
    comboSituacao = new JComboBox<>();
    btnDefinir = new JButton();

    setClosable(true);
    setIconifiable(true);
    setMaximizable(true);
    setResizable(true);
    setTitle("Alterar Situação de Transporte");
    setPreferredSize(new Dimension(500, 565));
    setVisible(true);

    title.setFont(Constantes.FONTE_TITULO);
    title.setHorizontalAlignment(SwingConstants.CENTER);
    title.setLabelFor(this);
    title.setText(getTitle());
    title.setPreferredSize(new Dimension(70, 25));

    GroupLayout painelHeaderLayout = new GroupLayout(painelHeader);
    painelHeader.setLayout(painelHeaderLayout);
    painelHeaderLayout.setHorizontalGroup(painelHeaderLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(painelHeaderLayout.createSequentialGroup()
        .addContainerGap(31, Short.MAX_VALUE)
        .addComponent(title, GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        .addContainerGap(31, Short.MAX_VALUE))
    );
    painelHeaderLayout.setVerticalGroup(painelHeaderLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(painelHeaderLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(title, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    painelLocalizar.setBorder(BorderFactory.createTitledBorder("Localizar transporte"));
    painelLocalizar.setPreferredSize(new Dimension(500, 225));

    labelNumero.setLabelFor(inputNumero);
    labelNumero.setText("Número:");
    labelNumero.setPreferredSize(new Dimension(60, 30));

    inputNumero.setToolTipText("Informe o número do transporte");
    inputNumero.setPreferredSize(new Dimension(125, 30));

    btnBuscar.setText("Buscar");
    btnBuscar.setToolTipText("Buscar o transporte com o número correspondente");
    btnBuscar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    btnBuscar.setPreferredSize(new Dimension(95, 30));
    getRootPane().setDefaultButton(btnBuscar);
    btnBuscar.addActionListener(this::buscaTransporte);

    labelTransporte.setLabelFor(textAreaTransporte);
    labelTransporte.setText("Descrição:");
    labelTransporte.setPreferredSize(new Dimension(125, 15));

    scrollPaneTransporte.setToolTipText("Informações sobre o transporte localizado");
    scrollPaneTransporte.setPreferredSize(new Dimension(500, 400));

    textAreaTransporte.setEditable(false);
    textAreaTransporte.setColumns(20);
    textAreaTransporte.setLineWrap(true);
    textAreaTransporte.setRows(5);
    textAreaTransporte.setTabSize(2);
    textAreaTransporte.setWrapStyleWord(true);
    scrollPaneTransporte.setViewportView(textAreaTransporte);

    GroupLayout painelLocalizarLayout = new GroupLayout(painelLocalizar);
    painelLocalizar.setLayout(painelLocalizarLayout);
    painelLocalizarLayout.setHorizontalGroup(painelLocalizarLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(painelLocalizarLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(painelLocalizarLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
          .addComponent(labelTransporte, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(painelLocalizarLayout.createSequentialGroup()
            .addGroup(painelLocalizarLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
              .addGroup(painelLocalizarLayout.createSequentialGroup()
                .addComponent(labelNumero, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNumero, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(btnBuscar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
              .addComponent(scrollPaneTransporte, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addContainerGap())))
    );
    painelLocalizarLayout.setVerticalGroup(painelLocalizarLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(painelLocalizarLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(painelLocalizarLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
          .addComponent(labelNumero, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
          .addComponent(inputNumero, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
          .addComponent(btnBuscar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(labelTransporte, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(scrollPaneTransporte, GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    painelSituacao.setBorder(BorderFactory.createTitledBorder("Alterar situação"));
    painelSituacao.setPreferredSize(new Dimension(450, 67));

    labelSituacao.setLabelFor(inputNumero);
    labelSituacao.setText("Nova situação:");
    labelSituacao.setPreferredSize(new Dimension(60, 30));

    comboSituacao.setEnabled(false);
    comboSituacao.setPreferredSize(new Dimension(125, 30));

    btnDefinir.setText("Definir");
    btnDefinir.setToolTipText("Definir a situação selecionada para o transporte");
    btnDefinir.setCursor(new Cursor(Cursor.HAND_CURSOR));
    btnDefinir.setEnabled(false);
    btnDefinir.setPreferredSize(new Dimension(95, 30));
    btnDefinir.addActionListener(this::defineNovaSituacao);

    GroupLayout painelSituacaoLayout = new GroupLayout(painelSituacao);
    painelSituacao.setLayout(painelSituacaoLayout);
    painelSituacaoLayout.setHorizontalGroup(painelSituacaoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(painelSituacaoLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(labelSituacao, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(comboSituacao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
        .addComponent(btnDefinir, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    painelSituacaoLayout.setVerticalGroup(painelSituacaoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(painelSituacaoLayout.createSequentialGroup()
        .addGap(7, 7, 7)
        .addGroup(painelSituacaoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
          .addComponent(labelSituacao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
          .addComponent(comboSituacao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
          .addComponent(btnDefinir, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    GroupLayout layout = new GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
          .addComponent(painelLocalizar, GroupLayout.PREFERRED_SIZE, 450, GroupLayout.PREFERRED_SIZE)
          .addComponent(painelSituacao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
          .addComponent(painelHeader, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(20, Short.MAX_VALUE)
        .addComponent(painelHeader, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(painelLocalizar, GroupLayout.PREFERRED_SIZE, 337, GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(painelSituacao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        .addContainerGap(35, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void buscaTransporte(ActionEvent evt) {//GEN-FIRST:event_buscaTransporte
		try {
			int numero = Integer.parseInt(inputNumero.getText());
			Transporte t = transporteHandler.buscaPorNumero(numero);

			if (t == null) {
				JOptionPane.showMessageDialog(this, "Nenhum transporte encontrado para o número %d".formatted(numero), getTitle(), JOptionPane.WARNING_MESSAGE);
				return;
			}

			this.transporte = t;
			mostraTransporte();
			ativaPainelSituacao();
		} catch (Exception e) {
			e.printStackTrace(System.err);
			JOptionPane.showMessageDialog(this, "Erro ao buscar transporte...\nVerifique o número digitado e tente novamente!", getTitle(), JOptionPane.ERROR_MESSAGE);
		}
  }//GEN-LAST:event_buscaTransporte

  private void defineNovaSituacao(ActionEvent evt) {//GEN-FIRST:event_defineNovaSituacao
		Estado estado = (Estado) comboSituacao.getSelectedItem();

		String[] opcoes = {"Sim", "Não"};
		int resposta = JOptionPane.showOptionDialog(this,
			"Tem certeza que deseja definir a situação do transporte de número %d para %s?\nEsta ação não pode ser desfeita!".formatted(transporte.getNumero(), estado),
			getTitle(), JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[1]);

		if (resposta != 0) {
			return;
		}

		boolean sucesso = transporteHandler.definirNovaSituacao(transporte, estado);

		if (!sucesso) {
			JOptionPane.showMessageDialog(this, "Ocorreu um erro ao tentar realizar a operação...\nTente novamente!", getTitle(), JOptionPane.ERROR_MESSAGE);
			return;
		}

		JOptionPane.showMessageDialog(this, "Operação realizada com sucesso!", getTitle(), JOptionPane.INFORMATION_MESSAGE);
		inputNumero.setText("");
		mostraTransporte();
		desativaPainelSituacao();
  }//GEN-LAST:event_defineNovaSituacao

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JButton btnDefinir;
  private JComboBox<Estado> comboSituacao;
  private JFormattedTextField inputNumero;
  private JTextArea textAreaTransporte;
  // End of variables declaration//GEN-END:variables
}
