package views;

import dados.Estado;
import dados.Transporte;
import handlers.TransporteHandler;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import java.util.List;

/**
 * {@link JInternalFrame} que contém o formulário utilizado
 * para buscar e alterar a situação de determinado {@link Transporte}.
 *
 * @author Lucas da Paz
 */
public class SituacaoTransporte extends javax.swing.JInternalFrame {
	private final TransporteHandler transporteHandler;
	private Transporte transporte;

	/**
	 * Inicializa um novo frame {@link SituacaoTransporte}.
	 */
	public SituacaoTransporte() {
		transporteHandler = TransporteHandler.getHandler();
		initComponents();
	}

	/**
	 * Habilita o painel de escolha de situação do {@link Transporte}.
	 */
	private void ativaPainelSituacao() {
		List<Estado> estados = switch (transporte.getSituacao()) {
			case PENDENTE -> List.of(Estado.CANCELADO);
			case ALOCADO -> List.of(Estado.TERMINADO, Estado.CANCELADO);
			default -> null;
		};

		if (estados == null) {
			JOptionPane.showMessageDialog(this,
				"O transporte de número %d já foi finalizado e não pode ter sua situação alterada".formatted(transporte.getNumero()),
				getTitle(), JOptionPane.INFORMATION_MESSAGE);
			return;
		}

		comboSituacao.setModel(new DefaultComboBoxModel<>(estados.toArray(Estado[]::new)));
		comboSituacao.setEnabled(true);
		btnDefinir.setEnabled(true);
	}

	/**
	 * Desabilita o painel de escolha de situação do {@link Transporte}.
	 */
	private void desativaPainelSituacao() {
		comboSituacao.setSelectedIndex(-1);
		comboSituacao.setEnabled(false);
		btnDefinir.setEnabled(false);
	}

	/**
	 * Mostra as informações do {@link Transporte} buscado na
	 * área de texto.
	 */
	private void mostraTransporte() {
		textAreaTransporte.setText(transporte.toString());
		if (transporte.getDrone() != null) {
			textAreaTransporte.append("\n> Transportador -> %s".formatted(transporte.getDrone()));
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    javax.swing.JPanel painelHeader = new javax.swing.JPanel();
    javax.swing.JLabel title = new javax.swing.JLabel();
    javax.swing.JPanel painelLocalizar = new javax.swing.JPanel();
    javax.swing.JLabel labelNumero = new javax.swing.JLabel();
    inputNumero = new javax.swing.JFormattedTextField(Constantes.FORMATO_INTEIRO);
    javax.swing.JButton btnBuscar = new javax.swing.JButton();
    javax.swing.JLabel labelTransporte = new javax.swing.JLabel();
    javax.swing.JScrollPane scrollPaneTransporte = new javax.swing.JScrollPane();
    textAreaTransporte = new javax.swing.JTextArea();
    javax.swing.JPanel painelSituacao = new javax.swing.JPanel();
    javax.swing.JLabel labelSituacao = new javax.swing.JLabel();
    comboSituacao = new javax.swing.JComboBox<>();
    btnDefinir = new javax.swing.JButton();

    setClosable(true);
    setIconifiable(true);
    setMaximizable(true);
    setResizable(true);
    setTitle("Alterar Situação de Transporte");
    setPreferredSize(new java.awt.Dimension(500, 550));
    setVisible(true);

    title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    title.setLabelFor(this);
    title.setText(getTitle());

    javax.swing.GroupLayout painelHeaderLayout = new javax.swing.GroupLayout(painelHeader);
    painelHeader.setLayout(painelHeaderLayout);
    painelHeaderLayout.setHorizontalGroup(
      painelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(painelHeaderLayout.createSequentialGroup()
        .addContainerGap(31, Short.MAX_VALUE)
        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        .addContainerGap(31, Short.MAX_VALUE))
    );
    painelHeaderLayout.setVerticalGroup(
      painelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(painelHeaderLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(title)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    painelLocalizar.setBorder(javax.swing.BorderFactory.createTitledBorder("Localizar transporte"));
    painelLocalizar.setPreferredSize(new java.awt.Dimension(500, 225));

    labelNumero.setLabelFor(inputNumero);
    labelNumero.setText("Número:");
    labelNumero.setPreferredSize(new java.awt.Dimension(60, 30));

    inputNumero.setToolTipText("Informe o número do transporte");
    inputNumero.setPreferredSize(new java.awt.Dimension(125, 30));

    btnBuscar.setText("Buscar");
    btnBuscar.setToolTipText("Buscar o transporte com o número correspondente");
    btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnBuscar.setPreferredSize(new java.awt.Dimension(95, 30));
    getRootPane().setDefaultButton(btnBuscar);
    btnBuscar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buscaTransporte(evt);
      }
    });

    labelTransporte.setLabelFor(textAreaTransporte);
    labelTransporte.setText("Descrição:");
    labelTransporte.setPreferredSize(new java.awt.Dimension(125, 15));

    scrollPaneTransporte.setToolTipText("Informações sobre o transporte localizado");
    scrollPaneTransporte.setPreferredSize(new java.awt.Dimension(500, 400));

    textAreaTransporte.setEditable(false);
    textAreaTransporte.setColumns(20);
    textAreaTransporte.setLineWrap(true);
    textAreaTransporte.setRows(5);
    textAreaTransporte.setTabSize(2);
    textAreaTransporte.setWrapStyleWord(true);
    scrollPaneTransporte.setViewportView(textAreaTransporte);

    javax.swing.GroupLayout painelLocalizarLayout = new javax.swing.GroupLayout(painelLocalizar);
    painelLocalizar.setLayout(painelLocalizarLayout);
    painelLocalizarLayout.setHorizontalGroup(
      painelLocalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(painelLocalizarLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(painelLocalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(labelTransporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(painelLocalizarLayout.createSequentialGroup()
            .addGroup(painelLocalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(painelLocalizarLayout.createSequentialGroup()
                .addComponent(labelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(scrollPaneTransporte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addContainerGap())))
    );
    painelLocalizarLayout.setVerticalGroup(
      painelLocalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(painelLocalizarLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(painelLocalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(inputNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(labelTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(scrollPaneTransporte, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    painelSituacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Alterar situação"));
    painelSituacao.setPreferredSize(new java.awt.Dimension(450, 67));

    labelSituacao.setLabelFor(inputNumero);
    labelSituacao.setText("Nova situação:");
    labelSituacao.setPreferredSize(new java.awt.Dimension(60, 30));

    comboSituacao.setEnabled(false);
    comboSituacao.setPreferredSize(new java.awt.Dimension(125, 30));

    btnDefinir.setText("Definir");
    btnDefinir.setToolTipText("Definir a situação selecionada para o transporte");
    btnDefinir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnDefinir.setEnabled(false);
    btnDefinir.setPreferredSize(new java.awt.Dimension(95, 30));
    btnDefinir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        defineNovaSituacao(evt);
      }
    });

    javax.swing.GroupLayout painelSituacaoLayout = new javax.swing.GroupLayout(painelSituacao);
    painelSituacao.setLayout(painelSituacaoLayout);
    painelSituacaoLayout.setHorizontalGroup(
      painelSituacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(painelSituacaoLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(labelSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(comboSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
        .addComponent(btnDefinir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    painelSituacaoLayout.setVerticalGroup(
      painelSituacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(painelSituacaoLayout.createSequentialGroup()
        .addGap(7, 7, 7)
        .addGroup(painelSituacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(comboSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnDefinir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(painelLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(painelSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(painelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(20, Short.MAX_VALUE)
        .addComponent(painelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(painelLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(painelSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(35, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void buscaTransporte(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaTransporte
		try {
			int numero = Integer.parseInt(inputNumero.getText());
			Transporte t = transporteHandler.buscaPorNumero(numero);

			if (t == null) {
				JOptionPane.showMessageDialog(this, "Nenhum transporte encontrado para o número %d".formatted(numero), getTitle(), JOptionPane.WARNING_MESSAGE);
				return;
			}

			this.transporte = t;
			mostraTransporte();
			ativaPainelSituacao();
		} catch (Exception e) {
			e.printStackTrace(System.err);
			JOptionPane.showMessageDialog(this, "Erro ao buscar transporte...\nVerifique o número digitado e tente novamente!", getTitle(), JOptionPane.ERROR_MESSAGE);
		}
  }//GEN-LAST:event_buscaTransporte

  private void defineNovaSituacao(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defineNovaSituacao
		Estado estado = (Estado) comboSituacao.getSelectedItem();

		String[] opcoes = {"Sim", "Não"};
		int resposta = JOptionPane.showOptionDialog(this,
			"Tem certeza que deseja definir a situação do transporte de número %d para %s?\nEsta ação não pode ser desfeita!".formatted(transporte.getNumero(), estado),
			getTitle(), JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[1]);

		if (resposta != 0) {
			return;
		}

		boolean sucesso = transporteHandler.definirNovaSituacao(transporte, estado);

		if (!sucesso) {
			JOptionPane.showMessageDialog(this, "Ocorreu um erro ao tentar realizar a operação...\nTente novamente!", getTitle(), JOptionPane.ERROR_MESSAGE);
			return;
		}

		JOptionPane.showMessageDialog(this, "Operação realizada com sucesso!", getTitle(), JOptionPane.INFORMATION_MESSAGE);
		inputNumero.setText("");
		mostraTransporte();
		desativaPainelSituacao();
  }//GEN-LAST:event_defineNovaSituacao

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnDefinir;
  private javax.swing.JComboBox<Estado> comboSituacao;
  private javax.swing.JFormattedTextField inputNumero;
  private javax.swing.JTextArea textAreaTransporte;
  // End of variables declaration//GEN-END:variables
}
