package views;

import dados.Drone;
import dados.DronePessoal;
import handlers.DroneHandler;

import java.awt.Event;
import java.awt.Frame;
import java.awt.event.WindowEvent;
import java.text.NumberFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 * @author Lucas da Paz
 */
public class CadastroDrone extends javax.swing.JFrame {

	private final NumberFormat integerFormat;
	private final NumberFormat decimalFormat;
	private final DroneHandler droneHandler;

	/**
	 * Creates new form CadastroDrones
	 */
	public CadastroDrone() {
		integerFormat = NumberFormat.getIntegerInstance(Locale.ENGLISH);
		integerFormat.setGroupingUsed(false);
		decimalFormat = NumberFormat.getInstance(Locale.ENGLISH);
		decimalFormat.setGroupingUsed(false);
		droneHandler = new DroneHandler();
		initComponents();
		setVisible(true);
	}

	private void limpaCampos() {
		inputCodigo.setText("");
		inputCustoFixo.setText("");
		inputAutonomia.setText("");
		inputMaxPessoasPessoal.setText("");
	}

	private void limpaMensagens() {
		textAreaMensagens.setText("");
	}

	private void notifica(String mensagem, int tipo) {
		textAreaMensagens.append("%n%s%n".formatted(mensagem));
		JOptionPane.showMessageDialog(this, mensagem, getTitle(), tipo);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    painelHeader = new javax.swing.JPanel();
    title = new javax.swing.JLabel();
    painelDrone = new javax.swing.JPanel();
    labelCodigo = new javax.swing.JLabel();
    inputCodigo = new javax.swing.JFormattedTextField(integerFormat);
    labelCustoFixo = new javax.swing.JLabel();
    inputCustoFixo = new javax.swing.JFormattedTextField(decimalFormat);
    labelAutonomia = new javax.swing.JLabel();
    inputAutonomia = new javax.swing.JFormattedTextField(decimalFormat);
    painelAbas = new javax.swing.JTabbedPane();
    tabDronePessoal = new javax.swing.JPanel();
    labelMaxPessoasPessoal = new javax.swing.JLabel();
    inputMaxPessoasPessoal = new javax.swing.JFormattedTextField(integerFormat);
    painelMensagens = new javax.swing.JPanel();
    scrollPaneMensagens = new javax.swing.JScrollPane();
    textAreaMensagens = new javax.swing.JTextArea();
    painelBotoes = new javax.swing.JPanel();
    btnCadastrar = new javax.swing.JButton();
    btnListar = new javax.swing.JButton();
    btnLimpar = new javax.swing.JButton();
    btnSair = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Cadastro de Drone");
    setName(""); // NOI18N
    setPreferredSize(new java.awt.Dimension(600, 550));

    title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    title.setLabelFor(this);
    title.setText("Cadastro de Drones");

    javax.swing.GroupLayout painelHeaderLayout = new javax.swing.GroupLayout(painelHeader);
    painelHeader.setLayout(painelHeaderLayout);
    painelHeaderLayout.setHorizontalGroup(
      painelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelHeaderLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    painelHeaderLayout.setVerticalGroup(
      painelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(painelHeaderLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(title)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    painelDrone.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações gerais"));

    labelCodigo.setLabelFor(inputCodigo);
    labelCodigo.setText("Código:");
    labelCodigo.setPreferredSize(new java.awt.Dimension(125, 15));

    inputCodigo.setPreferredSize(new java.awt.Dimension(125, 30));

    labelCustoFixo.setLabelFor(inputCustoFixo);
    labelCustoFixo.setText("Custo fixo:");
    labelCustoFixo.setPreferredSize(new java.awt.Dimension(125, 15));

    inputCustoFixo.setPreferredSize(new java.awt.Dimension(125, 30));

    labelAutonomia.setLabelFor(inputAutonomia);
    labelAutonomia.setText("Autonomia");
    labelAutonomia.setPreferredSize(new java.awt.Dimension(125, 15));

    inputAutonomia.setPreferredSize(new java.awt.Dimension(125, 30));

    javax.swing.GroupLayout painelDroneLayout = new javax.swing.GroupLayout(painelDrone);
    painelDrone.setLayout(painelDroneLayout);
    painelDroneLayout.setHorizontalGroup(
      painelDroneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(painelDroneLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(painelDroneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(inputCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
          .addComponent(labelCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(18, 18, Short.MAX_VALUE)
        .addGroup(painelDroneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(inputCustoFixo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(labelCustoFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, Short.MAX_VALUE)
        .addGroup(painelDroneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(inputAutonomia, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
          .addComponent(labelAutonomia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    painelDroneLayout.setVerticalGroup(
      painelDroneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(painelDroneLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(painelDroneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(painelDroneLayout.createSequentialGroup()
            .addComponent(labelCustoFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(inputCustoFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(painelDroneLayout.createSequentialGroup()
            .addGroup(painelDroneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(labelAutonomia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(labelCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(painelDroneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(inputAutonomia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(inputCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    labelMaxPessoasPessoal.setLabelFor(inputMaxPessoasPessoal);
    labelMaxPessoasPessoal.setText("Máximo de Pessoas");
    labelMaxPessoasPessoal.setPreferredSize(new java.awt.Dimension(125, 15));

    inputMaxPessoasPessoal.setPreferredSize(new java.awt.Dimension(125, 30));

    javax.swing.GroupLayout tabDronePessoalLayout = new javax.swing.GroupLayout(tabDronePessoal);
    tabDronePessoal.setLayout(tabDronePessoalLayout);
    tabDronePessoalLayout.setHorizontalGroup(
      tabDronePessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(tabDronePessoalLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(tabDronePessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(labelMaxPessoasPessoal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(inputMaxPessoasPessoal, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
        .addContainerGap(452, Short.MAX_VALUE))
    );
    tabDronePessoalLayout.setVerticalGroup(
      tabDronePessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(tabDronePessoalLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(labelMaxPessoasPessoal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(inputMaxPessoasPessoal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    painelAbas.addTab("Drone Pessoal", tabDronePessoal);

    painelMensagens.setBorder(javax.swing.BorderFactory.createTitledBorder("Mensagens"));

    textAreaMensagens.setEditable(false);
    textAreaMensagens.setColumns(45);
    textAreaMensagens.setRows(5);
    textAreaMensagens.setTabSize(2);
    textAreaMensagens.setWrapStyleWord(true);
    textAreaMensagens.setFocusable(false);
    scrollPaneMensagens.setViewportView(textAreaMensagens);

    javax.swing.GroupLayout painelMensagensLayout = new javax.swing.GroupLayout(painelMensagens);
    painelMensagens.setLayout(painelMensagensLayout);
    painelMensagensLayout.setHorizontalGroup(
      painelMensagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(painelMensagensLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(scrollPaneMensagens)
        .addContainerGap())
    );
    painelMensagensLayout.setVerticalGroup(
      painelMensagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(painelMensagensLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(scrollPaneMensagens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    btnCadastrar.setText("Cadastrar");
    btnCadastrar.setToolTipText("Cadastrar novo drone");
    btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnCadastrar.setPreferredSize(new java.awt.Dimension(95, 30));
    getRootPane().setDefaultButton(btnCadastrar);
    btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCadastrarActionPerformed(evt);
      }
    });

    btnListar.setText("Listar");
    btnListar.setToolTipText("Listar, no campo Mensagens, os drones cadastrados");
    btnListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnListar.setPreferredSize(new java.awt.Dimension(95, 30));
    btnListar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnListarActionPerformed(evt);
      }
    });

    btnLimpar.setText("Limpar");
    btnLimpar.setToolTipText("Limpar os campos de texto e de mensagem");
    btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnLimpar.setPreferredSize(new java.awt.Dimension(95, 30));
    btnLimpar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLimparActionPerformed(evt);
      }
    });

    btnSair.setText("Sair");
    btnSair.setToolTipText("Encerrar a aplicação");
    btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnSair.setPreferredSize(new java.awt.Dimension(95, 30));
    btnSair.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSairActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
    painelBotoes.setLayout(painelBotoesLayout);
    painelBotoesLayout.setHorizontalGroup(
      painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(painelBotoesLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    painelBotoesLayout.setVerticalGroup(
      painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(painelBotoesLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(painelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(painelDrone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(painelAbas, javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(painelMensagens, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(painelBotoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(18, Short.MAX_VALUE)
        .addComponent(painelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(painelDrone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(painelAbas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(painelMensagens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 26, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
		try {
			int codigo = Integer.parseInt(inputCodigo.getText());
			double custoFixo = Double.parseDouble(inputCustoFixo.getText());
			double autonomia = Double.parseDouble(inputAutonomia.getText());
			int maximoPessoas = Integer.parseInt(inputMaxPessoasPessoal.getText());

			Drone novoDrone = new DronePessoal(codigo, custoFixo, autonomia, maximoPessoas);
			boolean sucesso = droneHandler.cadastraDrone(novoDrone);

			if (!sucesso) {
				notifica("Já existe um drone cadastrado com o código %d".formatted(codigo), JOptionPane.WARNING_MESSAGE);
				return;
			}

			notifica("Drone cadastrado com sucesso!", JOptionPane.INFORMATION_MESSAGE);
			limpaCampos();
		} catch (Exception e) {
			notifica(
				"Erro ao cadastrar drone...\nVerifique se os campos estão preenchidos corretamente e tente novamente!"
					.formatted(e.getMessage()),
				JOptionPane.ERROR_MESSAGE);
		}
  }//GEN-LAST:event_btnCadastrarActionPerformed

  private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
		List<Drone> drones = droneHandler.buscaTodos();
		if (drones.isEmpty()) {
			notifica("Nenhum drone cadastrado!", JOptionPane.INFORMATION_MESSAGE);
			return;
		}

		StringBuilder sb = new StringBuilder("\nDrones cadastrados:\n");
		drones.forEach(d -> sb.append(d).append("\n"));
		sb.append("\n");
		textAreaMensagens.append(sb.toString());
  }//GEN-LAST:event_btnListarActionPerformed

  private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
		limpaCampos();
		limpaMensagens();
  }//GEN-LAST:event_btnLimparActionPerformed

  private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
		limpaCampos();
		dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
  }//GEN-LAST:event_btnSairActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCadastrar;
  private javax.swing.JButton btnLimpar;
  private javax.swing.JButton btnListar;
  private javax.swing.JButton btnSair;
  private javax.swing.JFormattedTextField inputAutonomia;
  private javax.swing.JFormattedTextField inputCodigo;
  private javax.swing.JFormattedTextField inputCustoFixo;
  private javax.swing.JFormattedTextField inputMaxPessoasPessoal;
  private javax.swing.JLabel labelAutonomia;
  private javax.swing.JLabel labelCodigo;
  private javax.swing.JLabel labelCustoFixo;
  private javax.swing.JLabel labelMaxPessoasPessoal;
  private javax.swing.JTabbedPane painelAbas;
  private javax.swing.JPanel painelBotoes;
  private javax.swing.JPanel painelDrone;
  private javax.swing.JPanel painelHeader;
  private javax.swing.JPanel painelMensagens;
  private javax.swing.JScrollPane scrollPaneMensagens;
  private javax.swing.JPanel tabDronePessoal;
  private javax.swing.JTextArea textAreaMensagens;
  private javax.swing.JLabel title;
  // End of variables declaration//GEN-END:variables
}
